name: Version
concurrency: version

on:
  workflow_dispatch:
    inputs:
      project:
        description: Name of the project
        required: true
        type: string

jobs:
  version:
    runs-on: ubuntu-latest
    name: New version for project ${{inputs.project}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Version
        run: yarn nx run ${{inputs.project}}:version --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
